//this file defines all the types in the game that both monsters and moves have.

export enum Type {
  WATER = 'water',
  FIRE = 'fire',
  NATURE = 'nature',
  ICE = 'ice',
  ELECTRIC = 'electric',
  TOXIC = 'toxic',
  SHADOW = 'shadow',
  ESP = 'esp',
  LIGHT = 'light',
  EARTH = 'earth',
  METAL = 'metal',
  WIND = 'wind',
  BEAST = 'beast',
  ARCANE = 'arcane'
}

/**
 * this assumes attacker -> defender, for instance the first line is WATER as an attacker and the second is WATER as a defender
 */
export const typeChart = {
  [Type.WATER]: {
    [Type.WATER]: 0.5,
    [Type.FIRE]: 2,
    [Type.NATURE]: 0.5,
    [Type.ICE]: 0.5,
    [Type.ELECTRIC]: 2,
    [Type.TOXIC]: 2,
    [Type.SHADOW]: 1,
    [Type.ESP]: 1,
    [Type.LIGHT]: 1,
    [Type.EARTH]: 2,
    [Type.METAL]: 1,
    [Type.WIND]: 1,
    [Type.BEAST]: 1,
    [Type.ARCANE]: 0.5
  },
  [Type.FIRE]: {
    [Type.WATER]: 0.5,
    [Type.FIRE]: 0.5,
    [Type.NATURE]: 2,
    [Type.ICE]: 2,
    [Type.ELECTRIC]: 1,
    [Type.TOXIC]: 2,
    [Type.SHADOW]: 1,
    [Type.ESP]: 1,
    [Type.LIGHT]: 1,
    [Type.EARTH]: 0.5,
    [Type.METAL]: 2,
    [Type.WIND]: 1,
    [Type.BEAST]: 0.5,
    [Type.ARCANE]: 0.5
  },
  [Type.NATURE]: {
    [Type.WATER]: 2,
    [Type.FIRE]: 0.5,
    [Type.NATURE]: 0.5,
    [Type.ICE]: 1,
    [Type.ELECTRIC]: 1,
    [Type.TOXIC]: 0.5,
    [Type.SHADOW]: 1,
    [Type.ESP]: 1,
    [Type.LIGHT]: 1,
    [Type.EARTH]: 2,
    [Type.METAL]: 0.5,
    [Type.WIND]: 0.5,
    [Type.BEAST]: 1,
    [Type.ARCANE]: 1
  },
  [Type.ICE]: {
    [Type.WATER]: 0.5,
    [Type.FIRE]: 2,
    [Type.NATURE]: 2,
    [Type.ICE]: 0.5,
    [Type.ELECTRIC]: 1,
    [Type.TOXIC]: 1,
    [Type.SHADOW]: 1,
    [Type.ESP]: 1,
    [Type.LIGHT]: 1,
    [Type.EARTH]: 1,
    [Type.METAL]: 0.5,
    [Type.WIND]: 2,
    [Type.BEAST]: 1,
    [Type.ARCANE]: 1
  },
  [Type.ELECTRIC]: {
    [Type.WATER]: 2,
    [Type.FIRE]: 1,
    [Type.NATURE]: 0.5,
    [Type.ICE]: 1,
    [Type.ELECTRIC]: 0,
    [Type.TOXIC]: 1,
    [Type.SHADOW]: 1,
    [Type.ESP]: 1,
    [Type.LIGHT]: 1,
    [Type.EARTH]: 0,
    [Type.METAL]: 2,
    [Type.WIND]: 2,
    [Type.BEAST]: 1,
    [Type.ARCANE]: 1
  },
  [Type.TOXIC]: {
    [Type.WATER]: 2,
    [Type.FIRE]: 0.5,
    [Type.NATURE]: 2,
    [Type.ICE]: 1,
    [Type.ELECTRIC]: 1,
    [Type.TOXIC]: 0,
    [Type.SHADOW]: 1,
    [Type.ESP]: 1,
    [Type.LIGHT]: 1,
    [Type.EARTH]: 1,
    [Type.METAL]: 0,
    [Type.WIND]: 1,
    [Type.BEAST]: 2,
    [Type.ARCANE]: 1
  },
  [Type.SHADOW]: {
    [Type.WATER]: 1,
    [Type.FIRE]: 1,
    [Type.NATURE]: 1,
    [Type.ICE]: 1,
    [Type.ELECTRIC]: 1,
    [Type.TOXIC]: 0.5,
    [Type.SHADOW]: 0.5,
    [Type.ESP]: 2,
    [Type.LIGHT]: 2,
    [Type.EARTH]: 1,
    [Type.METAL]: 1,
    [Type.WIND]: 1,
    [Type.BEAST]: 1,
    [Type.ARCANE]: 1
  },
  [Type.ESP]: {
    [Type.WATER]: 1,
    [Type.FIRE]: 1,
    [Type.NATURE]: 1,
    [Type.ICE]: 1,
    [Type.ELECTRIC]: 1,
    [Type.TOXIC]: 2,
    [Type.SHADOW]: 0.5,
    [Type.ESP]: 0.5,
    [Type.LIGHT]: 1,
    [Type.EARTH]: 1,
    [Type.METAL]: 1,
    [Type.WIND]: 1,
    [Type.BEAST]: 2,
    [Type.ARCANE]: 2
  },
  [Type.LIGHT]: {
    [Type.WATER]: 1,
    [Type.FIRE]: 0.5,
    [Type.NATURE]: 1,
    [Type.ICE]: 2,
    [Type.ELECTRIC]: 1,
    [Type.TOXIC]: 1,
    [Type.SHADOW]: 2,
    [Type.ESP]: 1,
    [Type.LIGHT]: 0.5,
    [Type.EARTH]: 1,
    [Type.METAL]: 0.5,
    [Type.WIND]: 1,
    [Type.BEAST]: 1,
    [Type.ARCANE]: 1
  },
  [Type.EARTH]: {
    [Type.WATER]: 1,
    [Type.FIRE]: 2,
    [Type.NATURE]: 1,
    [Type.ICE]: 1,
    [Type.ELECTRIC]: 2,
    [Type.TOXIC]: 2,
    [Type.SHADOW]: 1,
    [Type.ESP]: 1,
    [Type.LIGHT]: 1,
    [Type.EARTH]: 0.5,
    [Type.METAL]: 2,
    [Type.WIND]: 0,
    [Type.BEAST]: 0.5,
    [Type.ARCANE]: 1
  },
  [Type.METAL]: {
    [Type.WATER]: 0.5,
    [Type.FIRE]: 0.5,
    [Type.NATURE]: 1,
    [Type.ICE]: 2,
    [Type.ELECTRIC]: 0.5,
    [Type.TOXIC]: 1,
    [Type.SHADOW]: 1,
    [Type.ESP]: 1,
    [Type.LIGHT]: 2,
    [Type.EARTH]: 0.5,
    [Type.METAL]: 0.5,
    [Type.WIND]: 1,
    [Type.BEAST]: 2,
    [Type.ARCANE]: 1
  },
  [Type.WIND]: {
    [Type.WATER]: 1,
    [Type.FIRE]: 2,
    [Type.NATURE]: 1,
    [Type.ICE]: 1,
    [Type.ELECTRIC]: 1,
    [Type.TOXIC]: 2,
    [Type.SHADOW]: 1,
    [Type.ESP]: 1,
    [Type.LIGHT]: 1,
    [Type.EARTH]: 2,
    [Type.METAL]: 1,
    [Type.WIND]: 0.5,
    [Type.BEAST]: 1,
    [Type.ARCANE]: 1
  },
  [Type.BEAST]: {
    [Type.WATER]: 1,
    [Type.FIRE]: 0.5,
    [Type.NATURE]: 1,
    [Type.ICE]: 1,
    [Type.ELECTRIC]: 1,
    [Type.TOXIC]: 1,
    [Type.SHADOW]: 1,
    [Type.ESP]: 1,
    [Type.LIGHT]: 1,
    [Type.EARTH]: 1,
    [Type.METAL]: 0.5,
    [Type.WIND]: 0.5,
    [Type.BEAST]: 1,
    [Type.ARCANE]: 2
  },
  [Type.ARCANE]: {
    [Type.WATER]: 1,
    [Type.FIRE]: 1,
    [Type.NATURE]: 1,
    [Type.ICE]: 1,
    [Type.ELECTRIC]: 1,
    [Type.TOXIC]: 1,
    [Type.SHADOW]: 2,
    [Type.ESP]: 1,
    [Type.LIGHT]: 0.5,
    [Type.EARTH]: 1,
    [Type.METAL]: 0.5,
    [Type.WIND]: 1,
    [Type.BEAST]: 2,
    [Type.ARCANE]: 2
  }
}

export function effectiveness(attackType: Type, defendType: Type) {
  //receives two types, and returns the effectiveness of the first type towards the second in the form of a float.
  return typeChart[attackType][defendType]
}
